// Tercüman cümle kitabı — diş tedavisinde en sık kullanılan cümleler [tr, en, de, ar]
export const PHRASE_LANGS = ["tr", "en", "de", "ar"] as const;
export const SPEECH: Record<string, string> = { tr: "tr-TR", en: "en-GB", de: "de-DE", ar: "ar-SA" };
export const PHRASES: { cat: string; p: [string, string, string, string] }[] = [
  { cat: "greet", p: ["Hoş geldiniz! Ben tercümanınızım.", "Welcome! I am your interpreter.", "Willkommen! Ich bin Ihr Dolmetscher.", "أهلاً بك! أنا مترجمك."] },
  { cat: "greet", p: ["Lütfen bekleme salonunda oturun, birkaç dakika içinde çağıracağız.", "Please take a seat in the waiting room; we will call you in a few minutes.", "Bitte nehmen Sie im Wartezimmer Platz, wir rufen Sie in wenigen Minuten auf.", "يرجى الجلوس في غرفة الانتظار، سنناديك خلال دقائق."] },
  { cat: "greet", p: ["Pasaportunuzu görebilir miyim?", "May I see your passport?", "Darf ich Ihren Reisepass sehen?", "هل يمكنني رؤية جواز سفرك؟"] },
  { cat: "health", p: ["Bugün herhangi bir ilaç aldınız mı?", "Have you taken any medication today?", "Haben Sie heute Medikamente eingenommen?", "هل تناولت أي دواء اليوم؟"] },
  { cat: "health", p: ["Herhangi bir ilaca alerjiniz var mı?", "Are you allergic to any medication?", "Sind Sie gegen Medikamente allergisch?", "هل لديك حساسية من أي دواء؟"] },
  { cat: "health", p: ["Kan sulandırıcı kullanıyor musunuz?", "Do you take blood thinners?", "Nehmen Sie Blutverdünner?", "هل تتناول مميعات الدم؟"] },
  { cat: "health", p: ["Bugün bir şey yediniz mi?", "Have you eaten anything today?", "Haben Sie heute etwas gegessen?", "هل أكلت شيئاً اليوم؟"] },
  { cat: "treat", p: ["Şimdi lokal anestezi yapacağız; küçük bir iğne batması hissedeceksiniz.", "We will now give you a local anaesthetic; you will feel a small pinch.", "Wir geben Ihnen jetzt eine örtliche Betäubung; Sie spüren einen kleinen Stich.", "سنعطيك الآن تخديراً موضعياً؛ ستشعر بوخزة صغيرة."] },
  { cat: "treat", p: ["Ağrı hissederseniz lütfen sol elinizi kaldırın.", "If you feel any pain, please raise your left hand.", "Wenn Sie Schmerzen haben, heben Sie bitte die linke Hand.", "إذا شعرت بأي ألم، ارفع يدك اليسرى من فضلك."] },
  { cat: "treat", p: ["Ağzınızı biraz daha açın lütfen.", "Please open your mouth a little wider.", "Bitte öffnen Sie den Mund etwas weiter.", "افتح فمك أكثر قليلاً من فضلك."] },
  { cat: "treat", p: ["Isırın ve dişlerinizi sıkın.", "Bite down and close your teeth together.", "Bitte zubeißen und die Zähne zusammenpressen.", "عض وأطبق أسنانك معاً."] },
  { cat: "treat", p: ["Ağzınızı çalkalayabilirsiniz.", "You can rinse your mouth now.", "Sie können jetzt den Mund ausspülen.", "يمكنك المضمضة الآن."] },
  { cat: "treat", p: ["Şimdi röntgen / tomografi çekeceğiz.", "We will now take an X-ray / CT scan.", "Wir machen jetzt ein Röntgenbild / CT.", "سنقوم الآن بتصوير الأشعة / المقطعية."] },
  { cat: "treat", p: ["Ölçü alacağız; bir dakika kadar sürecek.", "We will take an impression; it takes about one minute.", "Wir nehmen einen Abdruck; das dauert etwa eine Minute.", "سنأخذ طبعة للأسنان؛ تستغرق دقيقة تقريباً."] },
  { cat: "treat", p: ["Rengi birlikte seçelim. Hangisini beğendiniz?", "Let's choose the shade together. Which one do you like?", "Wählen wir gemeinsam die Farbe. Welche gefällt Ihnen?", "لنختر اللون معاً. أيهما يعجبك؟"] },
  { cat: "treat", p: ["İşlem tamamlandı. Çok iyi iş çıkardınız!", "The procedure is finished. You did very well!", "Die Behandlung ist abgeschlossen. Das haben Sie sehr gut gemacht!", "انتهى الإجراء. لقد أحسنت!"] },
  { cat: "pain", p: ["Ağrınızı 0 ile 10 arasında puanlar mısınız?", "Can you rate your pain from 0 to 10?", "Wie stark sind Ihre Schmerzen von 0 bis 10?", "هل يمكنك تقييم ألمك من 0 إلى 10؟"] },
  { cat: "pain", p: ["Ağrı keskin mi, zonklayıcı mı?", "Is the pain sharp or throbbing?", "Ist der Schmerz stechend oder pochend?", "هل الألم حاد أم نابض؟"] },
  { cat: "pain", p: ["Sıcak veya soğukta hassasiyet var mı?", "Is it sensitive to hot or cold?", "Ist es empfindlich auf Heiß oder Kalt?", "هل هناك حساسية للحار أو البارد؟"] },
  { cat: "after", p: ["Uyuşukluk 2–3 saat sürebilir; o süre içinde bir şey yemeyin.", "The numbness may last 2–3 hours; please don't eat until it wears off.", "Die Betäubung kann 2–3 Stunden anhalten; bitte bis dahin nichts essen.", "قد يستمر التخدير 2–3 ساعات؛ لا تأكل حتى يزول."] },
  { cat: "after", p: ["İlk 24 saat sigara ve alkol kullanmayın.", "No smoking or alcohol for the first 24 hours.", "In den ersten 24 Stunden bitte nicht rauchen und keinen Alkohol trinken.", "لا تدخين ولا كحول خلال أول 24 ساعة."] },
  { cat: "after", p: ["Yüzünüze 15 dakika aralıklarla buz uygulayın.", "Apply ice to your face for 15 minutes at a time.", "Kühlen Sie das Gesicht jeweils 15 Minuten lang.", "ضع الثلج على وجهك لمدة 15 دقيقة في كل مرة."] },
  { cat: "after", p: ["İlk gün sıcak ve sert yiyeceklerden kaçının; ılık ve yumuşak yiyin.", "Avoid hot and hard food on the first day; eat soft, lukewarm food.", "Vermeiden Sie am ersten Tag heiße und harte Speisen; essen Sie weich und lauwarm.", "تجنب الطعام الساخن والصلب في اليوم الأول؛ تناول طعاماً طرياً فاتراً."] },
  { cat: "after", p: ["Antibiyotiği kutu bitene kadar düzenli kullanın.", "Take the antibiotics regularly until the pack is finished.", "Nehmen Sie das Antibiotikum regelmäßig, bis die Packung leer ist.", "تناول المضاد الحيوي بانتظام حتى تنتهي العلبة."] },
  { cat: "after", p: ["Hafif kanama normaldir; gazlı bezi 30 dakika ısırın.", "Light bleeding is normal; bite on the gauze for 30 minutes.", "Leichte Blutung ist normal; beißen Sie 30 Minuten auf den Tupfer.", "النزيف الخفيف طبيعي؛ عض على الشاش لمدة 30 دقيقة."] },
  { cat: "after", p: ["Herhangi bir sorunda koordinatörünüze WhatsApp'tan yazın.", "If you have any problem, message your coordinator on WhatsApp.", "Bei Problemen schreiben Sie Ihrem Koordinator per WhatsApp.", "في حال وجود أي مشكلة، راسل منسقك عبر واتساب."] },
  { cat: "logistics", p: ["Bir sonraki randevunuz yarın saat …", "Your next appointment is tomorrow at …", "Ihr nächster Termin ist morgen um …", "موعدك القادم غداً الساعة …"] },
  { cat: "logistics", p: ["Transfer aracınız otelin önünde sizi bekliyor olacak.", "Your transfer car will be waiting for you in front of the hotel.", "Ihr Transferfahrzeug wartet vor dem Hotel auf Sie.", "ستنتظرك سيارة النقل أمام الفندق."] },
  { cat: "logistics", p: ["Ödemeyi resepsiyonda kartla veya nakit yapabilirsiniz.", "You can pay at reception by card or cash.", "Sie können an der Rezeption mit Karte oder bar bezahlen.", "يمكنك الدفع في الاستقبال بالبطاقة أو نقداً."] },
  { cat: "logistics", p: ["Kalıcı dişleriniz için 3–6 ay sonra tekrar geleceksiniz.", "You will come back in 3–6 months for your permanent teeth.", "Für Ihre endgültigen Zähne kommen Sie in 3–6 Monaten wieder.", "ستعود بعد 3–6 أشهر لتركيب أسنانك الدائمة."] },
];
